In [ ]:
import pandas as pd
import matplotlib.pyplot as mlt
import numpy as np

In [ ]:
dataset=pd.read_csv('auto-mpg.csv')
dataset

In [ ]:
dataset[dataset['horsepower']=='?']

In [ ]:
#fill the ? mark with 50
#this method is not for exam is temporary
dataset.loc[dataset['horsepower']=='?','horsepower']=50
dataset[dataset['horsepower']=='?']

In [ ]:
dataset[dataset['horsepower']==50]

In [ ]:
#this method is appropriate
dataset.loc[dataset['horsepower']==50,'horsepower']=np.NaN
dataset[dataset['horsepower'].isna()]

In [ ]:
ipl=pd.read_csv('ipl-matches.csv')
ipl

In [ ]:
ipl.info()

In [ ]:
ipl.describe()

In [ ]:
ipl.shape[0]

### how many match is gone in superover

In [ ]:
ipl.head()

In [ ]:
ipl[ipl['SuperOver']=='Y'].shape[0]

In [ ]:
#how many matches won by toss winner of the match
ipl[ipl['TossWinner']==ipl['WinningTeam']].shape[0]

In [ ]:
#how many matches won by csk at kalkatta(conditon muki a to bracket karva padse)
ipl[(ipl['WinningTeam']=='Chennai Super Kings') & (ipl['City']=='Kolkata')].shape[0]

In [ ]:
#how many matches gt played (team1-home ground) (team2-away ground)
ipl[(ipl['Team1']=='Gujarat Titans') | (ipl['Team2']=='Gujarat Titans')].shape[0]

In [ ]:
#how many matches won by gt
ipl[ipl['WinningTeam']=='Gujarat Titans'].shape[0]

In [ ]:
#how many matches gt won the toss and elected to bat first
ipl[(ipl['TossWinner']=='Gujarat Titans') & (ipl['TossDecision']=='bat')].shape[0]

In [ ]:
#in how many matches rohit sharma declared man of the match
ipl[ipl['Player_of_Match']=='RG Sharma'].shape[0]

In [ ]:
ipl['Team1Players'][0]

# Set Index

In [ ]:
data={
    'name':['ramesh','suresh','mukesh'],
    'age':[20,26,30],
    'city':['amd','surat','baroda']
}

df=pd.DataFrame(data)
df

In [ ]:
df.set_index('age',drop=False)

In [ ]:
df

In [ ]:
df.set_index('age',drop=True)

In [ ]:
df

In [ ]:
df.set_index('age',drop=True,inplace=True)#inplace=False atle temporary

In [ ]:
df

In [ ]:
data={
    'name':['ramesh','suresh','mukesh'],
    'age':[20,26,30],
    'city':['amd','surat','baroda']
}

df=pd.DataFrame(data)
df

In [ ]:
df.set_index(['age','name'],drop=True)

# DATA FRAME ATTRIBUTE

In [ ]:
data={
    'name':['ramesh','suresh','mukesh'],
    'age':[20,26,30],
    'city':['amd','surat','baroda']
}

df=pd.DataFrame(data)
df

In [ ]:
df.shape

In [ ]:
df.size

In [ ]:
df.index

In [ ]:
df.keys()

In [ ]:
df.values

In [ ]:
df.ndim

In [ ]:
#difference between loc and iloc

In [ ]:
data={
    'name':['ramesh','suresh','keshav','nishant','kishor'],
    'age':[20,26,30,35,32],
    'city':['amd','surat','baroda','jamnagar','vapi']
}

df=pd.DataFrame(data)
df

In [ ]:
df[0:2]

In [ ]:
df[0::2]

In [ ]:
df.loc[0]

In [ ]:
# df[0]#its get error
df.iloc[0]#index no data type int hoy to j vaprvu

In [ ]:
df.loc[0:2]

In [ ]:
df.iloc[0:2]

In [ ]:
df.loc[2:4,'age']=40

In [ ]:
df

In [ ]:
df.iloc[2:4,'age']=40

In [ ]:
df.iloc[2:4,1]=50

In [ ]:
df

In [ ]:
df.loc[2:4,'xyz']=40

In [ ]:
df

In [ ]:
df.iloc[2:4,4]=39

In [ ]:
df['c']=[10,20,30,40,50]
df

In [ ]:
df.loc[df['age']==40,'new']=500

In [ ]:
df

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data={
    'name':['ramesh','suresh','shyam'],
    'age':[20,26,30],
    'city':['amd','surat','baroda']
}
df=pd.DataFrame(data)
df

In [ ]:
df.sample()

In [ ]:
df.sample(2)

In [ ]:
df.sample(4)

In [ ]:
df.sample(5,replace=True)

In [ ]:
df.nunique()#number of unique value

In [ ]:
df['age'].unique()#aama column kevu padse

In [ ]:
data={
    'a':[10,10,10],
    'b':[10,20,20],
    'c':[10,20,30]
}
df=pd.DataFrame(data)
df

In [ ]:
df.nunique()#aakha dataset nu unique value aapse

In [ ]:
df['b'].unique()#aa khali column ma j thase

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data={
    'name':['alice','charlie','bob','david'],
    'age':[23,32,20,26]
}
df=pd.DataFrame(data,['a','b','c','d'])
df

      name  age
a    alice   23
b  charlie   32
c      bob   20
d    david   26

In [3]:
df1=df.reset_index()

In [4]:
df1

  index     name  age
0     a    alice   23
1     b  charlie   32
2     c      bob   20
3     d    david   26

In [5]:
df2=df1.reset_index()
df2

   level_0 index     name  age
0        0     a    alice   23
1        1     b  charlie   32
2        2     c      bob   20
3        3     d    david   26

In [6]:
df1=df.reset_index(drop=True)
df1

      name  age
0    alice   23
1  charlie   32
2      bob   20
3    david   26

## APPLY() FUNCTION

In [7]:
data=[35,67,96,40]
s=pd.Series(data)
def fail_pass(x):
    return 'pass' if x>50 else 'fail'
result=s.apply(fail_pass)
result

0    fail
1    pass
2    pass
3    fail
dtype: object

In [8]:

data={
    'physics':[70,80,90],
    'chemistry':[65,75,85],
    'maths':[50,70,90]
}
df=pd.DataFrame(data)
df

   physics  chemistry  maths
0       70         65     50
1       80         75     70
2       90         85     90

In [9]:
result=df.apply(sum)#column
result

physics      240
chemistry    225
maths        210
dtype: int64

In [10]:
res=df.apply(sum,axis=1)#row
res

0    185
1    225
2    265
dtype: int64

In [11]:
result=df.apply(lambda x:x.sum())
result

physics      240
chemistry    225
maths        210
dtype: int64

In [ ]:
#add new column
df['total']=res
df
def g(x):
    if x<=200:
        return c
    if x>=200 and x=250:
        return b
    else:
        return a
a=df.apply(g)

In [12]:
df['total']=df.apply(sum,axis=1)
df

   physics  chemistry  maths  total
0       70         65     50    185
1       80         75     70    225
2       90         85     90    265

In [18]:
def g(x):
    if x<=200:
        return 'c'
    elif x>=200 and x<=250:
        return 'b'
    else:
        return 'a'
df['grade']=df['total'].apply(g)
df

   physics  chemistry  maths  total grade
0       70         65     50    185     c
1       80         75     70    225     b
2       90         85     90    265     a

In [22]:
data={
    'width':[1,2],
    'height':[3,4]
    }
df=pd.DataFrame(data)
df

   width  height
0      1       3
1      2       4

In [25]:
def get_stat(x):
    return [x['width']*x['height'],2*(x['width']+x['height'])]
df

   width  height
0      1       3
1      2       4

In [26]:
df.apply(get_stat,axis=1,result_type='expand')

   0   1
0  3   8
1  8  12

In [27]:
df.apply(get_stat,axis=1,result_type='broadcast')

   width  height
0      3       8
1      8      12

In [28]:
df.apply(get_stat,axis=1,result_type='reduce')

0     [3, 8]
1    [8, 12]
dtype: object

In [31]:
df.apply(get_stat,axis=1,result_type=None)

0     [3, 8]
1    [8, 12]
dtype: object

### sort values and sort index

In [33]:
data={
    'name':['alice','charlie','bob','david'],
    'score':[85,80,90,72]
}
df=pd.DataFrame(data)
df

      name  score
0    alice     85
1  charlie     80
2      bob     90
3    david     72

In [34]:
df.sort_values('score')

      name  score
3    david     72
1  charlie     80
0    alice     85
2      bob     90

In [35]:
df.sort_index()

      name  score
0    alice     85
1  charlie     80
2      bob     90
3    david     72

In [36]:
df.sort_values('score',ascending=False)

      name  score
2      bob     90
0    alice     85
1  charlie     80
3    david     72

In [37]:
df.set_index('name',inplace=True)
df.sort_index()

         score
name
alice       85
bob         90
charlie     80
david       72

In [38]:
df.dtypes

score    int64
dtype: object

In [46]:
data={
    'a':['1','2','3'],
    'b':['4','5','6'],
}
df=pd.DataFrame(data)
print("first when data is created\n",df.dtypes)
df['a']=df['a'].astype(int)
df.dtypes

first when data is created
 a    object
b    object
dtype: object

a     int32
b    object
dtype: object

## Replace Function

In [1]:
import pandas as pd
d1=pd.DataFrame({
    'marks':[80,85,0,90],
    'attendance':[75,80,0,85],
    'grade':['a','b','c','d']
})
d1

   marks  attendance grade
0     80          75     a
1     85          80     b
2      0           0     c
3     90          85     d

In [4]:
res=d1.replace(0,60)
res

   marks  attendance grade
0     80          75     a
1     85          80     b
2     60          60     c
3     90          85     d

In [5]:
res=d1.replace([80,85],[62,45])
res

   marks  attendance grade
0     62          75     a
1     45          62     b
2      0           0     c
3     90          45     d

In [7]:
res=d1.replace({
    80:39,
    75:80
})
res

   marks  attendance grade
0     39          80     a
1     85          39     b
2      0           0     c
3     90          85     d

In [1]:
d1['marks'].replace(80,65)

NameError: name 'd1' is not defined