In [3]:
import pandas as pd
import numpy as np

In [4]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[5,6],'B':[7,8]})
print(df1)
print("--------------")
print(df2)

   A  B
0  1  3
1  2  4
--------------
   A  B
0  5  7
1  6  8

In [5]:
pd.concat([df1,df2])

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [6]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[5,6],'B':[7,8]})
pd.concat([df1,df2],join='inner')

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [7]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[5,6],'B':[7,8]})
pd.concat([df1,df2],join='outer')

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [8]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[5,6],'B':[7,8]})
pd.concat([df1,df2],axis=1)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [9]:
pd.concat([df1,df2],ignore_index=True)

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [10]:
df1=pd.DataFrame({'D':[1,2],'B':[3,4]})
df2=pd.DataFrame({'E':[5,6],'A':[7,8]})
pd.concat([df1,df2],sort=True)

     A    B    D    E
0  NaN  3.0  1.0  NaN
1  NaN  4.0  2.0  NaN
0  7.0  NaN  NaN  5.0
1  8.0  NaN  NaN  6.0

In [24]:
employees=pd.DataFrame({
    'emp_id':[1,2,3,4],
    'name':['A','B','C','D'],
    'dept_id':[10,20,10,30]
})
print(employees)

department=pd.DataFrame({
    'dept_id':[10,20,40],
    'name':['IT','HR','Finance']
})
print(department)

   emp_id name  dept_id
0       1    A       10
1       2    B       20
2       3    C       10
3       4    D       30
   dept_id     name
0       10       IT
1       20       HR
2       40  Finance

In [25]:
pd.merge(employees,department,on='dept_id',how='outer')

   emp_id name_x  dept_id   name_y
0     1.0      A       10       IT
1     3.0      C       10       IT
2     2.0      B       20       HR
3     4.0      D       30      NaN
4     NaN    NaN       40  Finance

In [13]:
pd.merge(employees,department,on='dept_id',how='inner')

   emp_id name_x  dept_id name_y
0       1      A       10     IT
1       3      C       10     IT
2       2      B       20     HR

In [14]:
pd.merge(employees,department,on='dept_id',how='left')

   emp_id name_x  dept_id name_y
0       1      A       10     IT
1       2      B       20     HR
2       3      C       10     IT
3       4      D       30    NaN

In [15]:
pd.merge(employees,department,on='dept_id',how='right')

   emp_id name_x  dept_id   name_y
0     1.0      A       10       IT
1     3.0      C       10       IT
2     2.0      B       20       HR
3     NaN    NaN       40  Finance

In [36]:
employees=pd.DataFrame({
    'emp_id':[1,2,3,4],
    'name':['A','B','C','D'],
    'dept_aid':[10,20,10,30]
})
print(employees)

   emp_id name  dept_aid
0       1    A        10
1       2    B        20
2       3    C        10
3       4    D        30

In [38]:
pd.merge(employees,department,left_on='dept_aid',right_on="dept_id",sort=True,how='outer',indicator=True,suffixes=("_emp","_dept"))

   emp_id name_emp  dept_aid  dept_id name_dept      _merge
0     1.0        A      10.0     10.0        IT        both
1     3.0        C      10.0     10.0        IT        both
2     2.0        B      20.0     20.0        HR        both
3     4.0        D      30.0      NaN       NaN   left_only
4     NaN      NaN       NaN     40.0   Finance  right_only

In [39]:
pd.merge(employees,department,left_index=True,right_index=True)

   emp_id name_x  dept_aid  dept_id   name_y
0       1      A        10       10       IT
1       2      B        20       20       HR
2       3      C        10       40  Finance

In [40]:
df=pd.DataFrame({
    'id':['1','2','3','4'],
    'active':['y','y','y','y'],
    'name':['A','B','A','D']
})
df.dtypes
df['id']=df['id'].astype(int)
df['active']=df['active'].astype(bool)
df.dtypes
df['name']=df['name'].replace('A','P')
df

   id  active name
0   1    True    P
1   2    True    B
2   3    True    P
3   4    True    D