```
Steps

1.. define the problem(x,y)
2.. collect and prepare data(download and read file)
3.. data preprocessing
    i)data modify
    ii)data cleaning
4.. data split(train(80),test(20))
5.. model selection
6.. train the model
7.. testing the data
8.. iteration & improve the data
9.. deploy the model
```
_____
```
y=mx+c
where,
m=coefficient
c=intercept
```
____
```
error=residual
residual means predicted data-actual data
```

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("testdata.csv")
dataset

     x   y
0   15  49
1   23  63
2   18  58
3   23  60
4   24  58
5   22  61
6   22  60
7   19  63
8   19  60
9   16  52
10  24  62
11  11  30
12  24  59
13  16  49
14  23  68

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x       15 non-null     int64
 1   y       15 non-null     int64
dtypes: int64(2)
memory usage: 372.0 bytes

In [4]:
dataset.isna().sum()

x    0
y    0
dtype: int64

In [5]:
#1 method for extracting x
x=dataset.iloc[:,0:1]
x

     x
0   15
1   23
2   18
3   23
4   24
5   22
6   22
7   19
8   19
9   16
10  24
11  11
12  24
13  16
14  23

In [6]:
# 2 method for extracting x
x=dataset[['x']]#dimension
x

     x
0   15
1   23
2   18
3   23
4   24
5   22
6   22
7   19
8   19
9   16
10  24
11  11
12  24
13  16
14  23

In [7]:
type(x)

pandas.core.frame.DataFrame

In [8]:
y=dataset['y']
y

0     49
1     63
2     58
3     60
4     58
5     61
6     60
7     63
8     60
9     52
10    62
11    30
12    59
13    49
14    68
Name: y, dtype: int64

In [9]:
type(y)

pandas.core.series.Series

In [10]:
x.shape #valid shape

(15, 1)

In [11]:
y.shape #valid shape

(15,)

In [12]:
#aama split nathi karyu excel ma atle aaama split nai karta
from sklearn.linear_model import LinearRegression

In [13]:
lr=LinearRegression()
lr.fit(x,y)#MODEL READY

LinearRegression()

In [14]:
print(lr.coef_)#VALUE OF COEFICIENT

[1.8939483]

In [15]:
print(lr.intercept_) #VALUE OF INTERCEPT

19.047297297297284

In [16]:
ypred=lr.predict(x)
ypred

array([47.45652174, 62.60810811, 53.13836663, 62.60810811, 64.5020564 ,
       60.71415981, 60.71415981, 55.03231492, 55.03231492, 49.35047004,
       64.5020564 , 39.88072855, 64.5020564 , 49.35047004, 62.60810811])

```
MAE= Mean Absolute Error
MSE= Mean Squared Error
R2_SCORE
```

```
R2_SCORE
1=perfect fit model
<0=input data is wrong
```

In [17]:
from sklearn import metrics
print("MAE:",metrics.mean_absolute_error(y,ypred))

MAE: 3.7412847630238946

In [18]:
print("MSE:",metrics.mean_squared_error(y,ypred))

MSE: 22.292068155111636

In [19]:
print("R2_Score:",metrics.r2_score(y,ypred))

R2_Score: 0.7088287858527738

___

```
next model with training and testing data
```

In [22]:
df=pd.read_csv("placement_03-06.csv")
df

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   cgpa     200 non-null    float64
 1   package  200 non-null    float64
dtypes: float64(2)
memory usage: 3.3 KB

In [25]:
df.isna().sum()

cgpa       0
package    0
dtype: int64

In [33]:
x=df[['cgpa']]#x always in data frame
x

     cgpa
0    6.89
1    5.12
2    7.82
3    7.42
4    6.94
..    ...
195  6.93
196  5.89
197  7.21
198  7.63
199  6.22

[200 rows x 1 columns]

In [34]:
y=df['package']#y is always in series
y

0      3.26
1      1.98
2      3.25
3      3.67
4      3.57
       ...
195    2.46
196    2.57
197    3.24
198    3.96
199    2.33
Name: package, Length: 200, dtype: float64

In [37]:
x.shape#(row,column)

(200, 1)

In [38]:
y.shape

(200,)

In [39]:
from sklearn.model_selection import train_test_split

```
sequence of initialize train and test is fixed like in that pair first x 
train size=0.8
test size=0.2
```

In [75]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=1)

In [76]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(160, 1)
(40, 1)
(160,)
(40,)

In [77]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)#model ready

LinearRegression()

In [78]:
#testing
ypred=lr.predict(x_test)
print(ypred)

[2.9383335  4.36894346 3.18258398 1.89736121 3.49662031 3.35123312
 2.76968435 2.94996447 3.07208971 3.94441286 3.57222165 2.94996447
 2.75805338 2.64755911 3.67108494 3.2174769  3.97930579 2.90925606
 2.19395108 3.31052471 4.29915761 2.8918096  1.87409926 2.30444534
 3.62456104 2.12998071 3.9269664  2.36841571 1.5716939  2.06601035
 2.31026083 3.6885314  3.5024358  3.03719679 2.57195777 2.39167766
 3.170953   3.82228762 3.15932203 2.94414898]

In [79]:
#make dataframe
diff=pd.DataFrame({"Actual":y_test,"Prediction":ypred})
diff

     Actual  Prediction
58     3.09    2.938333
40     4.02    4.368943
34     3.42    3.182584
102    1.37    1.897361
184    3.14    3.496620
198    3.96    3.351233
95     2.79    2.769684
4      3.57    2.949964
29     3.49    3.072090
168    3.52    3.944413
171    3.76    3.572222
18     2.98    2.949964
11     2.60    2.758053
89     2.72    2.647559
110    3.76    3.671085
118    2.88    3.217477
159    4.08    3.979306
35     2.87    2.909256
136    2.10    2.193951
59     3.31    3.310525
51     3.79    4.299158
16     2.35    2.891810
44     1.86    1.874099
94     2.42    2.304445
31     3.89    3.624561
162    2.55    2.129981
38     4.36    3.926966
28     2.24    2.368416
193    1.94    1.571694
27     2.16    2.066010
47     3.26    2.310261
165    4.08    3.688531
194    3.67    3.502436
177    3.64    3.037197
176    3.23    2.571958
97     2.84    2.391678
174    2.99    3.170953
73     4.03    3.822288
69     2.94    3.159322
172    2.51    2.944149

In [80]:
print("CO-EFICIENT:",lr.coef_)#VALUE OF COEFICIENT

CO-EFICIENT: [0.58154877]

In [81]:
print("INTERCEPT:",lr.intercept_) #VALUE OF INTERCEPT

INTERCEPT: -1.0859839580358033

In [82]:
from sklearn import metrics
print("MAE:",metrics.mean_absolute_error(y_test,ypred))
print("MSE:",metrics.mean_squared_error(y_test,ypred))
print("R2_Score:",metrics.r2_score(y_test,ypred))

MAE: 0.29931188593316804
MSE: 0.1370062519255722
R2_Score: 0.7283345498058083